# Generated by Django 4.0.2 on 2022-03-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default=None, max_length=200, null=True, upload_to='images'),
        ),
    ]
