# Generated by Django 4.0.2 on 2022-03-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('mobilephone', 'mobilephone'), ('laptop', 'laptop')], max_length=200, null=True),
        ),
    ]
