# Generated by Django 3.1.7 on 2022-05-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20220519_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('book', 'book'), ('mobilephone', 'mobilephone'), ('laptop', 'laptop')], max_length=200, null=True),
        ),
    ]
