# Generated by Django 3.1.7 on 2022-05-20 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20220519_2108'),
        ('product', '0007_auto_20220520_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('mobilephone', 'mobilephone'), ('laptop', 'laptop'), ('book', 'book')], max_length=200, null=True),
        ),
    ]
