# Generated by Django 3.1.7 on 2022-05-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20220520_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('book', 'book'), ('mobilephone', 'mobilephone'), ('laptop', 'laptop')], max_length=200, null=True),
        ),
    ]
