# Generated by Django 3.1.7 on 2022-05-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20220520_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('laptop', 'laptop'), ('mobilephone', 'mobilephone'), ('book', 'book')], max_length=200, null=True),
        ),
    ]
