# Generated by Django 3.1.7 on 2022-05-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20220520_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='price',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='quantity',
        ),
        migrations.AddField(
            model_name='shipment',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('book', 'book'), ('laptop', 'laptop'), ('mobilephone', 'mobilephone')], max_length=200, null=True),
        ),
    ]
