# Generated by Django 3.1.7 on 2022-05-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20220520_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('mobilephone', 'mobilephone'), ('laptop', 'laptop'), ('book', 'book')], max_length=200, null=True),
        ),
    ]
