# Generated by Django 4.0.2 on 2022-03-25 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('ram', models.CharField(blank=True, max_length=200, null=True)),
                ('cpu', models.CharField(blank=True, max_length=200, null=True)),
                ('camera', models.CharField(blank=True, max_length=200, null=True)),
                ('audio', models.CharField(blank=True, max_length=200, null=True)),
                ('keyboard', models.CharField(blank=True, max_length=200, null=True)),
                ('communications_network', models.CharField(blank=True, max_length=200, null=True)),
                ('enternal_port', models.CharField(blank=True, max_length=200, null=True)),
                ('ac_acdopted', models.CharField(blank=True, max_length=200, null=True)),
                ('battery', models.CharField(blank=True, max_length=200, null=True)),
                ('vga', models.CharField(blank=True, max_length=200, null=True)),
                ('screen', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
